### ISSUE TITLE
Telegram group

### ISSUE THREAD

**Issue by davidhm** [AlienHoboken/Tremulous-X-Server#3]
Hey, this might be a long shot but, does anybody in here have a mail list of the old XServer players? I was thinking of creating a telegram group to share experiences and drown in nostalgia lol. Do you think it's a good idea? Let me know what you think. Btw, my username on the game was xConguitox.

**Comment by deepusudhakar** [comment]
Doublestuffed and I (deepu) would be interested.

**Comment by followthegraph** [comment]
Tundrasama reporting -- can't use Telegram though because of duplicate numbers.

**Comment by Tundrasama** [comment]
Tundrasama here -- can't use Telegram though because of duplicate phone numbers.

**Comment by AlienHoboken** [comment]
@davidhm @deepusudhakar @Tundrasama I could probably get a list together, do you still want it?

**Comment by davidhm** [comment]
Go ahead
